#ifndef DEFINES_H
#define DEFINES_H

// Synth constants
#define SAMPLE_RATE 44100
#define BEATS_PER_MINUTE 125
#define NOTES_PER_BEAT 4
#define SAMPLES_PER_NOTE (60 * 44100 / (BEATS_PER_MINUTE * NOTES_PER_BEAT))

// Instrument constants
#define MAX_NUM_INSTRUMENTS 4
#define MAX_COMMANDS 32
#define MAX_COMMAND_PARAMS 16

// Song data
#define PATTERNS_PER_INSTRUMENT 62
#define NOTES_PER_PATTERN 16
#define HLD 1
#define NOTES_PER_SONG (PATTERNS_PER_INSTRUMENT * NOTES_PER_PATTERN)

#define ENVELOPE_ID 1
#define OSCILLATOR_ID 2
#define STOREVAL_ID 3
#define OPERATION_ID 4
#define FILTER_ID 5
#define PANNING_ID 6
#define OUTPUT_ID 7
#define ACCUMULATE_ID 8
#define INSTRUMENT_END 0

#define OSCILLATOR_SINE 0x01
#define OSCILLATOR_SQUARE 0x02
#define OSCILLATOR_SAW 0x04
#define OSCILLATOR_TRIANGLE 0x08
#define OSCILLATOR_NOISE 0x10
#define OSCILLATOR_LFO 0x20

#define FILTER_LOWPASS 1
#define FILTER_HIGHPASS 2
#define FILTER_BANDSTOP 3
#define FILTER_BANDPASS 4
#define FILTER_ALLPASS 7
#define FILTER_PEAK 8

#define OPERATOR_MUL 1
#define OPERATOR_MULP 2

#endif // DEFINES_H
